// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      /* case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; */
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /* static const FirebaseOptions android = FirebaseOptions(
     apiKey: 'AIzaSyAMEu9KBjnRq5o-tFDSJSTc7WhccVe2-rw',
    appId: '1:164968813795:android:5e2c7b4f6b563c639861d6',
    messagingSenderId: '164968813795',
    projectId: 'qwafil-36c89',
    storageBucket: 'qwafil-36c89.firebasestorage.app', 
  );
 
  static const FirebaseOptions ios = FirebaseOptions(
     apiKey: 'AIzaSyBz5es6MHh9cqmYqjCIkduiA-638D_hn_8',
    appId: '1:164968813795:ios:cab498699a31a2049861d6',
    messagingSenderId: '164968813795',
    projectId: 'qwafil-36c89',
    storageBucket: 'qwafil-36c89.firebasestorage.app',
    iosBundleId: 'sta.sa.qwafil.qwafil', 
  );*/
}
